// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqchxcrrzixqeywsbmfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxY2h4Y3Jyeml4cWV5d3NibWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTAzNDMsImV4cCI6MjA2MTI2NjM0M30.i3HsZEf92Tp6OJlD3fHICJdTYeJgEPXWZF8sXszO4cc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);